### PR TITLE
Added SSD

### PR DESCRIPTION
**Pull request by oswynb**
Added differentiation between Block Standard and Fast storage

### CODE REVIEW

**Comment by tranma** [comment]
can you prettify the case/if in Infer.hs? try to line up the eqT so we're clear which case is casting which type

also indent 2 spaces in this package, I hadth decreed and thou shalt follow

**Comment by oswynb** [comment]
As you will, Darth Tran

**Comment by tranma** [comment]
I find your lack of tests disturbing

**Comment by tranma** [comment]
just add the prism and fold tests for SSD

there is currently no test for Infer.hs,  I guess we should generate some example SourceDict and test them at some point

**Pull request merged**
