### PR TITLE
Add neutron rx/tx and disk io + vogue

### PR DESCRIPTION
**Pull request by oswynb**
What it says on the box.

Also vogues a few files.

### CODE REVIEW

**Comment by tranma** [comment]
I know it's just the same as cpu, but can you add tests?

**Comment by oswynb** [comment]
roger

**Comment by olorin** [comment]
Yeah, looks good pending tests.

**Comment by tranma** [comment]
also I don't see the definition for valDiskReads etc. in Tags?

**Comment by oswynb** [comment]
You had already defined the required tags, I just added in the supporting types.

**Comment by tranma** [comment]
cool. What happened to travis anyway? Shouldn't it be reporting here?

**Comment by oswynb** [comment]
Travis should indeed be reporting here, unsure why it isn't. Either way travis build now passes: https://travis-ci.org/anchor/ceilometer-common

**Pull request merged**
